### ISSUE TITLE
Data table mapping

### ISSUE THREAD

**Issue by lkraider** [securestate/termineter#3]
Are there plans to map and parse the data tables from the standard?

**Comment by zeroSteiner** [comment]
Are there specific tables you're looking to parse? There are classes in the ```c1219.access``` package documented [here](http://termineter.readthedocs.org/en/latest/c1219/access/index.html) that are used by some of the modules in the framework. The classes are organized by their decade and exist for general, log, security and telephone.

**Comment by Scoo10** [comment]
I have the problem in communication  c1218IO....

the program termineter send data to smart meter but no respon or reciving
data in pc...



who solution the problem??

resguards

2015-06-18 11:10 GMT-05:00 Spencer McIntyre <notifications@github.com>:

**Comment by zeroSteiner** [comment]
@Scoo10 that's an unrelated issue. I'd appreciate you opening a separate ticket for discussion on it. Thanks!

**Comment by lkraider** [comment]
@zeroSteiner I would like for example to get the meter reading. What would be the process to read that, including the table decade and its format?

**Comment by zeroSteiner** [comment]
The information can be read from the meter, but you'll have to refer to the C12.19 standards to find which table it's in and how it's formatted. Termineter doesn't have a module right now to directly read and parse the usage information.

**Comment by lkraider** [comment]
Understood, we are working on that. You can close this ticket if that's not something on Termineters roadmap for now.

**Comment by zeroSteiner** [comment]
Great, if you get anything working feel free to submit a pull request! Unfortunately it is not something I'm actively pursuing now.
