### ISSUE TITLE
C1218IOError('failed 3 times to correctly send a frame'

### ISSUE THREAD

**Issue by Scoo10** [securestate/termineter#7]
smart meter in Mexico, bran  IUSA.  to connect RS232 serial cable probe for meter.  use a Windows  a python. the same error.

I have done with communication program if there is response from the  samrt meter and if there is.

**Comment by Scoo10** [comment]
![image](https://user-images.githubusercontent.com/10051969/36388603-0d405380-1562-11e8-85c6-690c0341addf.png)

**Comment by Scoo10** [comment]
![image](https://user-images.githubusercontent.com/10051969/36388786-9be5a5c2-1562-11e8-87b5-04a507c5e73c.png)

**Comment by zeroSteiner** [comment]
Can you set the log level to DEBUG and repeat the steps? My guess is that you're using incorrect serial settings so the probe can't communicate with the meter.

**Comment by Scoo10** [comment]
can you help me in the configuration of the Debug

what are the steps?



2018-02-19 12:51 GMT-06:00 Spencer McIntyre <notifications@github.com>:

**Comment by zeroSteiner** [comment]
Start the program with the `-L DEBUG` option. You can find more details from the `--help` menu.

**Comment by zeroSteiner** [comment]
I'm going to close this issue out due to inactivity. If you're still experiencing it, please respond to the preceding message in this thread and we'll re-open it. Thanks.

**Comment by Scoo10** [comment]
Good Day

One Cuestion Plase

did you program termineter  you can access to smart meter?



2018-02-27 16:40 GMT-06:00 Spencer McIntyre <notifications@github.com>:
