### ISSUE TITLE
Access to Digital  Smart Meters program Termineter

### ISSUE THREAD

**Issue by Scoo10** [securestate/termineter#8]
did  you can access to digital smart meter  with program Termineter.. 

did you optical probe use?

I failed in all attempts

**Comment by zeroSteiner** [comment]
I don't understand this issue. These questions seem like they are answered in the [README.md](https://github.com/securestate/termineter/tree/master/README.md). If you're having trouble, you'll need to be alot more descriptive as to what you're trying and what the results are.

**Comment by Scoo10** [comment]
which is the maximum time of transmission of data through the optical probe?

**Comment by zeroSteiner** [comment]
The default timeout is 1 second. See [here](https://github.com/securestate/termineter/blob/master/lib/termineter/utilities.py#L47).

**Comment by Arashahi** [comment]
Thanks for your app bro

**Comment by Arashahi** [comment]
I’m using a usb optical probe iec not an anci 
Is there any way to use the iec optical probe

**Comment by zeroSteiner** [comment]
@Arashahi No, only ANSI probes are supported. I've never had an IEC one to test with so only the North American standard is supported.

**Comment by robert-lee2** [comment]
ANSI and IEC probes have their TX and RX on opposite sides.  You may be able to get an IEC optical probe to work with an ANSI meter if you rotate the probe 180 degrees.

**Comment by Arashahi** [comment]
Ok bro thank you any way

**Comment by Arashahi** [comment]
So I’ve to change the 360 dg the iec probe,and run the  termineter, I’m runing Kali Linux any help or command line will be 
appreciated

**Comment by Arashahi** [comment]
Dear zero I’ve lil problem with ftdi driver installation 
Think can not install it properly

**Comment by zeroSteiner** [comment]
Sorry to hear that but driver installation issues are outside the scope of this project and are not something I can provide support for simply do to the limited resources available to me.

**Comment by Arashahi** [comment]
Ok tanx bro 🙏🏻
