### ISSUE TITLE
Error code c12-18 

### ISSUE THREAD

**Issue by Arashahi** [securestate/termineter#9]
Dear zero As I’ve accepted that this error because of communication codes that you wrote in c12-18 and our smart meters hers is wrote in iec 62056-21 codes not 12-18 or else   Could you write new code for this type of meters that we could check the security of them too. Best regards

**Comment by Arashahi** [comment]
And also I’ve the meters and just need the app to connect and if you tell me what you need any report and detail we will be able to write this down too

**Comment by zeroSteiner** [comment]
No, I neither the desire nor the means to implement any of the IEC standards.
